version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["bash", "-c", "rm -f /usr/src/app/tmp/pids/server.pid && bin/rails db:migrate && bundle exec rails s -b '0.0.0.0'"]
    ports:
      - "3000:3000"
    volumes:
       - .:/usr/src/app
    environment:
      - RAILS_ENV=development
      - TZ=Asia/Tokyo
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
       - .env
    networks:
      - app-network

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fitapp_api_development
      MYSQL_USER: ${DATABASE_DEV_USER}
      MYSQL_PASSWORD: ${DATABASE_DEV_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    external: true
