name: Deploy Rails API to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fitapp-api"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Wait for deployment to complete
        run: sleep 120  # デプロイ完了を待つ時間（適宜調整）

      - name: Run database migrations
        run: |
          heroku ps:scale web=0 --app fitapp-api  # Web dynoを停止
          heroku ps:scale web=1 --app fitapp-api  # Web dynoを再起動
          heroku run rails db:migrate --app fitapp-api
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
