name: Deploy Rails API to Heroku

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行される

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15  
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fitapp-api" # Herokuのアプリ名
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
